-- Generated by Haxe 4.2.1+bf9ff69
local _hx_hidden = {__id__=true, hx__closures=true, super=true, prototype=true, __fields__=true, __ifields__=true, __class__=true, __properties__=true, __fields__=true, __name__=true}

_hx_array_mt = {
    __newindex = function(t,k,v)
        local len = t.length
        t.length =  k >= len and (k + 1) or len
        rawset(t,k,v)
    end
}

function _hx_is_array(o)
    return type(o) == "table"
        and o.__enum__ == nil
        and getmetatable(o) == _hx_array_mt
end



function _hx_tab_array(tab, length)
    tab.length = length
    return setmetatable(tab, _hx_array_mt)
end



function _hx_print_class(obj, depth)
    local first = true
    local result = ''
    for k,v in pairs(obj) do
        if _hx_hidden[k] == nil then
            if first then
                first = false
            else
                result = result .. ', '
            end
            if _hx_hidden[k] == nil then
                result = result .. k .. ':' .. _hx_tostring(v, depth+1)
            end
        end
    end
    return '{ ' .. result .. ' }'
end

function _hx_print_enum(o, depth)
    if o.length == 2 then
        return o[0]
    else
        local str = o[0] .. "("
        for i = 2, (o.length-1) do
            if i ~= 2 then
                str = str .. "," .. _hx_tostring(o[i], depth+1)
            else
                str = str .. _hx_tostring(o[i], depth+1)
            end
        end
        return str .. ")"
    end
end

function _hx_tostring(obj, depth)
    if depth == nil then
        depth = 0
    elseif depth > 5 then
        return "<...>"
    end

    local tstr = _G.type(obj)
    if tstr == "string" then return obj
    elseif tstr == "nil" then return "null"
    elseif tstr == "number" then
        if obj == _G.math.POSITIVE_INFINITY then return "Infinity"
        elseif obj == _G.math.NEGATIVE_INFINITY then return "-Infinity"
        elseif obj == 0 then return "0"
        elseif obj ~= obj then return "NaN"
        else return _G.tostring(obj)
        end
    elseif tstr == "boolean" then return _G.tostring(obj)
    elseif tstr == "userdata" then
        local mt = _G.getmetatable(obj)
        if mt ~= nil and mt.__tostring ~= nil then
            return _G.tostring(obj)
        else
            return "<userdata>"
        end
    elseif tstr == "function" then return "<function>"
    elseif tstr == "thread" then return "<thread>"
    elseif tstr == "table" then
        if obj.__enum__ ~= nil then
            return _hx_print_enum(obj, depth)
        elseif obj.toString ~= nil and not _hx_is_array(obj) then return obj:toString()
        elseif _hx_is_array(obj) then
            if obj.length > 5 then
                return "[...]"
            else
                local str = ""
                for i=0, (obj.length-1) do
                    if i == 0 then
                        str = str .. _hx_tostring(obj[i], depth+1)
                    else
                        str = str .. "," .. _hx_tostring(obj[i], depth+1)
                    end
                end
                return "[" .. str .. "]"
            end
        elseif obj.__class__ ~= nil then
            return _hx_print_class(obj, depth)
        else
            local buffer = {}
            local ref = obj
            if obj.__fields__ ~= nil then
                ref = obj.__fields__
            end
            for k,v in pairs(ref) do
                if _hx_hidden[k] == nil then
                    _G.table.insert(buffer, _hx_tostring(k, depth+1) .. ' : ' .. _hx_tostring(obj[k], depth+1))
                end
            end

            return "{ " .. table.concat(buffer, ", ") .. " }"
        end
    else
        _G.error("Unknown Lua type", 0)
        return ""
    end
end

function _hx_error(obj)
    if obj.value then
        _G.print("runtime error:\n " .. _hx_tostring(obj.value));
    else
        _G.print("runtime error:\n " .. tostring(obj));
    end

    if _G.debug and _G.debug.traceback then
        _G.print(debug.traceback());
    end
end


local function _hx_obj_newindex(t,k,v)
    t.__fields__[k] = true
    rawset(t,k,v)
end

local _hx_obj_mt = {__newindex=_hx_obj_newindex, __tostring=_hx_tostring}

local function _hx_a(...)
  local __fields__ = {};
  local ret = {__fields__ = __fields__};
  local max = select('#',...);
  local tab = {...};
  local cur = 1;
  while cur < max do
    local v = tab[cur];
    __fields__[v] = true;
    ret[v] = tab[cur+1];
    cur = cur + 2
  end
  return setmetatable(ret, _hx_obj_mt)
end

local function _hx_e()
  return setmetatable({__fields__ = {}}, _hx_obj_mt)
end

local function _hx_o(obj)
  return setmetatable(obj, _hx_obj_mt)
end

local function _hx_new(prototype)
  return setmetatable({__fields__ = {}}, {__newindex=_hx_obj_newindex, __index=prototype, __tostring=_hx_tostring})
end

function _hx_field_arr(obj)
    res = {}
    idx = 0
    if obj.__fields__ ~= nil then
        obj = obj.__fields__
    end
    for k,v in pairs(obj) do
        if _hx_hidden[k] == nil then
            res[idx] = k
            idx = idx + 1
        end
    end
    return _hx_tab_array(res, idx)
end

local _hxClasses = {}
local Int = _hx_e();
local Dynamic = _hx_e();
local Float = _hx_e();
local Bool = _hx_e();
local Class = _hx_e();
local Enum = _hx_e();

local Array = _hx_e()
__defold_support_Script = _hx_e()
local Camera = _hx_e()
local String = _hx_e()
local Std = _hx_e()
local LevelTest = _hx_e()
local Loader = _hx_e()
local Math = _hx_e()
local Messages = _hx_e()
__astar_Node = _hx_e()
__astar_PathFinding = _hx_e()
__astar_Point = _hx_e()
__defold_CameraMessages = _hx_e()
__defold_CollectionproxyMessages = _hx_e()
__defold_GoMessages = _hx_e()
__defold_RenderMessages = _hx_e()
__defold_support_GuiScript = _hx_e()
__gui_GameGui = _hx_e()
__defold_support_RenderScript = _hx_e()
__renderer_Renderer = _hx_e()
__defold_support_Init = _hx_e()
__haxe_Log = _hx_e()
__haxe_ds_List = _hx_e()
__haxe_iterators_ArrayIterator = _hx_e()
__haxe_iterators_ArrayKeyValueIterator = _hx_e()
__renderer_RenderHelper = _hx_e()

local _hx_bind, _hx_bit, _hx_staticToInstance, _hx_funcToField, _hx_maxn, _hx_print, _hx_apply_self, _hx_box_mr, _hx_bit_clamp, _hx_table, _hx_bit_raw
local _hx_pcall_default = {};
local _hx_pcall_break = {};

Array.new = function() 
  local self = _hx_new(Array.prototype)
  Array.super(self)
  return self
end
Array.super = function(self) 
  _hx_tab_array(self, 0);
end
Array.prototype = _hx_e();
Array.prototype.concat = function(self,a) 
  local _g = _hx_tab_array({}, 0);
  local _g1 = 0;
  while (_g1 < self.length) do 
    local i = self[_g1];
    _g1 = _g1 + 1;
    _g:push(i);
  end;
  local _g1 = 0;
  while (_g1 < a.length) do 
    local i = a[_g1];
    _g1 = _g1 + 1;
    _g:push(i);
  end;
  do return _g end
end
Array.prototype.join = function(self,sep) 
  local tbl = ({});
  local _g_current = 0;
  while (_g_current < self.length) do 
    _g_current = _g_current + 1;
    _G.table.insert(tbl, Std.string(self[_g_current - 1]));
  end;
  do return _G.table.concat(tbl, sep) end
end
Array.prototype.pop = function(self) 
  if (self.length == 0) then 
    do return nil end;
  end;
  local ret = self[self.length - 1];
  self[self.length - 1] = nil;
  self.length = self.length - 1;
  do return ret end
end
Array.prototype.push = function(self,x) 
  self[self.length] = x;
  do return self.length end
end
Array.prototype.reverse = function(self) 
  local tmp;
  local i = 0;
  while (i < Std.int(self.length / 2)) do 
    tmp = self[i];
    self[i] = self[(self.length - i) - 1];
    self[(self.length - i) - 1] = tmp;
    i = i + 1;
  end;
end
Array.prototype.shift = function(self) 
  if (self.length == 0) then 
    do return nil end;
  end;
  local ret = self[0];
  if (self.length == 1) then 
    self[0] = nil;
  else
    if (self.length > 1) then 
      self[0] = self[1];
      _G.table.remove(self, 1);
    end;
  end;
  local tmp = self;
  tmp.length = tmp.length - 1;
  do return ret end
end
Array.prototype.slice = function(self,pos,_end) 
  if ((_end == nil) or (_end > self.length)) then 
    _end = self.length;
  else
    if (_end < 0) then 
      _end = _G.math.fmod((self.length - (_G.math.fmod(-_end, self.length))), self.length);
    end;
  end;
  if (pos < 0) then 
    pos = _G.math.fmod((self.length - (_G.math.fmod(-pos, self.length))), self.length);
  end;
  if ((pos > _end) or (pos > self.length)) then 
    do return _hx_tab_array({}, 0) end;
  end;
  local ret = _hx_tab_array({}, 0);
  local _g = pos;
  local _g1 = _end;
  while (_g < _g1) do 
    _g = _g + 1;
    ret:push(self[_g - 1]);
  end;
  do return ret end
end
Array.prototype.sort = function(self,f) 
  local i = 0;
  local l = self.length;
  while (i < l) do 
    local swap = false;
    local j = 0;
    local max = (l - i) - 1;
    while (j < max) do 
      if (f(self[j], self[j + 1]) > 0) then 
        local tmp = self[j + 1];
        self[j + 1] = self[j];
        self[j] = tmp;
        swap = true;
      end;
      j = j + 1;
    end;
    if (not swap) then 
      break;
    end;
    i = i + 1;
  end;
end
Array.prototype.splice = function(self,pos,len) 
  if ((len < 0) or (pos > self.length)) then 
    do return _hx_tab_array({}, 0) end;
  else
    if (pos < 0) then 
      pos = self.length - (_G.math.fmod(-pos, self.length));
    end;
  end;
  len = Math.min(len, self.length - pos);
  local ret = _hx_tab_array({}, 0);
  local _g = pos;
  local _g1 = pos + len;
  while (_g < _g1) do 
    _g = _g + 1;
    local i = _g - 1;
    ret:push(self[i]);
    self[i] = self[i + len];
  end;
  local _g = pos + len;
  local _g1 = self.length;
  while (_g < _g1) do 
    _g = _g + 1;
    local i = _g - 1;
    self[i] = self[i + len];
  end;
  self.length = self.length - len;
  do return ret end
end
Array.prototype.toString = function(self) 
  local tbl = ({});
  _G.table.insert(tbl, "[");
  _G.table.insert(tbl, self:join(","));
  _G.table.insert(tbl, "]");
  do return _G.table.concat(tbl, "") end
end
Array.prototype.unshift = function(self,x) 
  local len = self.length;
  local _g = 0;
  while (_g < len) do 
    _g = _g + 1;
    local i = _g - 1;
    self[len - i] = self[(len - i) - 1];
  end;
  self[0] = x;
end
Array.prototype.insert = function(self,pos,x) 
  if (pos > self.length) then 
    pos = self.length;
  end;
  if (pos < 0) then 
    pos = self.length + pos;
    if (pos < 0) then 
      pos = 0;
    end;
  end;
  local cur_len = self.length;
  while (cur_len > pos) do 
    self[cur_len] = self[cur_len - 1];
    cur_len = cur_len - 1;
  end;
  self[pos] = x;
end
Array.prototype.remove = function(self,x) 
  local _g = 0;
  local _g1 = self.length;
  while (_g < _g1) do 
    _g = _g + 1;
    local i = _g - 1;
    if (self[i] == x) then 
      local _g = i;
      local _g1 = self.length - 1;
      while (_g < _g1) do 
        _g = _g + 1;
        local j = _g - 1;
        self[j] = self[j + 1];
      end;
      self[self.length - 1] = nil;
      self.length = self.length - 1;
      do return true end;
    end;
  end;
  do return false end
end
Array.prototype.contains = function(self,x) 
  local _g = 0;
  local _g1 = self.length;
  while (_g < _g1) do 
    _g = _g + 1;
    if (self[_g - 1] == x) then 
      do return true end;
    end;
  end;
  do return false end
end
Array.prototype.indexOf = function(self,x,fromIndex) 
  local _end = self.length;
  if (fromIndex == nil) then 
    fromIndex = 0;
  else
    if (fromIndex < 0) then 
      fromIndex = self.length + fromIndex;
      if (fromIndex < 0) then 
        fromIndex = 0;
      end;
    end;
  end;
  local _g = fromIndex;
  while (_g < _end) do 
    _g = _g + 1;
    local i = _g - 1;
    if (x == self[i]) then 
      do return i end;
    end;
  end;
  do return -1 end
end
Array.prototype.lastIndexOf = function(self,x,fromIndex) 
  if ((fromIndex == nil) or (fromIndex >= self.length)) then 
    fromIndex = self.length - 1;
  else
    if (fromIndex < 0) then 
      fromIndex = self.length + fromIndex;
      if (fromIndex < 0) then 
        do return -1 end;
      end;
    end;
  end;
  local i = fromIndex;
  while (i >= 0) do 
    if (self[i] == x) then 
      do return i end;
    else
      i = i - 1;
    end;
  end;
  do return -1 end
end
Array.prototype.copy = function(self) 
  local _g = _hx_tab_array({}, 0);
  local _g1 = 0;
  while (_g1 < self.length) do 
    local i = self[_g1];
    _g1 = _g1 + 1;
    _g:push(i);
  end;
  do return _g end
end
Array.prototype.map = function(self,f) 
  local _g = _hx_tab_array({}, 0);
  local _g1 = 0;
  while (_g1 < self.length) do 
    local i = self[_g1];
    _g1 = _g1 + 1;
    _g:push(f(i));
  end;
  do return _g end
end
Array.prototype.filter = function(self,f) 
  local _g = _hx_tab_array({}, 0);
  local _g1 = 0;
  while (_g1 < self.length) do 
    local i = self[_g1];
    _g1 = _g1 + 1;
    if (f(i)) then 
      _g:push(i);
    end;
  end;
  do return _g end
end
Array.prototype.iterator = function(self) 
  do return __haxe_iterators_ArrayIterator.new(self) end
end
Array.prototype.keyValueIterator = function(self) 
  do return __haxe_iterators_ArrayKeyValueIterator.new(self) end
end
Array.prototype.resize = function(self,len) 
  if (self.length < len) then 
    self.length = len;
  else
    if (self.length > len) then 
      local _g = len;
      local _g1 = self.length;
      while (_g < _g1) do 
        _g = _g + 1;
        self[_g - 1] = nil;
      end;
      self.length = len;
    end;
  end;
end

__defold_support_Script.new = function() 
  local self = _hx_new()
  __defold_support_Script.super(self)
  return self
end
__defold_support_Script.super = function(self) 
end

Camera.new = function() 
  local self = _hx_new(Camera.prototype)
  Camera.super(self)
  return self
end
Camera.super = function(self) 
  __defold_support_Script.super(self);
end
Camera.toWorld = function(x,y) 
  local pos = _G.go.get_position("cam");
  local worldPos = __renderer_RenderHelper.instance:screenToWorld(x, y);
  do return _G.vmath.vector3(worldPos.x + pos.x, worldPos.y + pos.y, 0) end;
end
Camera.prototype = _hx_e();
Camera.prototype.init = function(self,_self) 
  _G.msg.post("#camera", __defold_CameraMessages.acquire_camera_focus);
  _G.msg.post(".", __defold_GoMessages.acquire_input_focus);
  Camera.zoom = 1;
end
Camera.prototype.final_ = function(self,_self) 
  _G.msg.post(".", __defold_GoMessages.release_input_focus);
end
Camera.prototype.on_input = function(self,_self,action_id,action) 
  if (action_id == Camera.WHEEL_DOWN) then 
    if (Camera.zoom < Camera.MAX_ZOOM) then 
      Camera.zoom = Camera.zoom + 0.05;
      __renderer_RenderHelper.instance.zoom = _hx_funcToField(Camera.zoom);
    end;
  else
    if (action_id == Camera.WHEEL_UP) then 
      if (Camera.zoom > Camera.MIN_ZOOM) then 
        Camera.zoom = Camera.zoom - 0.05;
        __renderer_RenderHelper.instance.zoom = _hx_funcToField(Camera.zoom);
      end;
    end;
  end;
  do return false end
end
Camera.__super__ = __defold_support_Script
setmetatable(Camera.prototype,{__index=__defold_support_Script.prototype})

String.new = function(string) 
  local self = _hx_new(String.prototype)
  String.super(self,string)
  self = string
  return self
end
String.super = function(self,string) 
end
String.__index = function(s,k) 
  if (k == "length") then 
    do return _G.string.len(s) end;
  else
    local o = String.prototype;
    local field = k;
    if ((function() 
      local _hx_1
      if ((_G.type(o) == "string") and ((String.prototype[field] ~= nil) or (field == "length"))) then 
      _hx_1 = true; elseif (o.__fields__ ~= nil) then 
      _hx_1 = o.__fields__[field] ~= nil; else 
      _hx_1 = o[field] ~= nil; end
      return _hx_1
    end )()) then 
      do return String.prototype[k] end;
    else
      if (String.__oldindex ~= nil) then 
        if (_G.type(String.__oldindex) == "function") then 
          do return String.__oldindex(s, k) end;
        else
          if (_G.type(String.__oldindex) == "table") then 
            do return String.__oldindex[k] end;
          end;
        end;
        do return nil end;
      else
        do return nil end;
      end;
    end;
  end;
end
String.indexOfEmpty = function(s,startIndex) 
  local length = _G.string.len(s);
  if (startIndex < 0) then 
    startIndex = length + startIndex;
    if (startIndex < 0) then 
      startIndex = 0;
    end;
  end;
  if (startIndex > length) then 
    do return length end;
  else
    do return startIndex end;
  end;
end
String.fromCharCode = function(code) 
  do return _G.string.char(code) end;
end
String.prototype = _hx_e();
String.prototype.toUpperCase = function(self) 
  do return _G.string.upper(self) end
end
String.prototype.toLowerCase = function(self) 
  do return _G.string.lower(self) end
end
String.prototype.indexOf = function(self,str,startIndex) 
  if (startIndex == nil) then 
    startIndex = 1;
  else
    startIndex = startIndex + 1;
  end;
  if (str == "") then 
    do return String.indexOfEmpty(self, startIndex - 1) end;
  end;
  local r = _G.string.find(self, str, startIndex, true);
  if ((r ~= nil) and (r > 0)) then 
    do return r - 1 end;
  else
    do return -1 end;
  end;
end
String.prototype.lastIndexOf = function(self,str,startIndex) 
  local ret = -1;
  if (startIndex == nil) then 
    startIndex = #self;
  end;
  while (true) do 
    local startIndex1 = ret + 1;
    if (startIndex1 == nil) then 
      startIndex1 = 1;
    else
      startIndex1 = startIndex1 + 1;
    end;
    local p;
    if (str == "") then 
      p = String.indexOfEmpty(self, startIndex1 - 1);
    else
      local r = _G.string.find(self, str, startIndex1, true);
      p = (function() 
        local _hx_1
        if ((r ~= nil) and (r > 0)) then 
        _hx_1 = r - 1; else 
        _hx_1 = -1; end
        return _hx_1
      end )();
    end;
    if (((p == -1) or (p > startIndex)) or (p == ret)) then 
      break;
    end;
    ret = p;
  end;
  do return ret end
end
String.prototype.split = function(self,delimiter) 
  local idx = 1;
  local ret = _hx_tab_array({}, 0);
  while (idx ~= nil) do 
    local newidx = 0;
    if (#delimiter > 0) then 
      newidx = _G.string.find(self, delimiter, idx, true);
    else
      if (idx >= #self) then 
        newidx = nil;
      else
        newidx = idx + 1;
      end;
    end;
    if (newidx ~= nil) then 
      ret:push(_G.string.sub(self, idx, newidx - 1));
      idx = newidx + #delimiter;
    else
      ret:push(_G.string.sub(self, idx, #self));
      idx = nil;
    end;
  end;
  do return ret end
end
String.prototype.toString = function(self) 
  do return self end
end
String.prototype.substring = function(self,startIndex,endIndex) 
  if (endIndex == nil) then 
    endIndex = #self;
  end;
  if (endIndex < 0) then 
    endIndex = 0;
  end;
  if (startIndex < 0) then 
    startIndex = 0;
  end;
  if (endIndex < startIndex) then 
    do return _G.string.sub(self, endIndex + 1, startIndex) end;
  else
    do return _G.string.sub(self, startIndex + 1, endIndex) end;
  end;
end
String.prototype.charAt = function(self,index) 
  do return _G.string.sub(self, index + 1, index + 1) end
end
String.prototype.charCodeAt = function(self,index) 
  do return _G.string.byte(self, index + 1) end
end
String.prototype.substr = function(self,pos,len) 
  if ((len == nil) or (len > (pos + #self))) then 
    len = #self;
  else
    if (len < 0) then 
      len = #self + len;
    end;
  end;
  if (pos < 0) then 
    pos = #self + pos;
  end;
  if (pos < 0) then 
    pos = 0;
  end;
  do return _G.string.sub(self, pos + 1, pos + len) end
end

Std.new = {}
Std.string = function(s) 
  do return _hx_tostring(s, 0) end;
end
Std.int = function(x) 
  if (not Math.isFinite(x) or Math.isNaN(x)) then 
    do return 0 end;
  else
    do return _hx_bit_clamp(x) end;
  end;
end

LevelTest.new = function() 
  local self = _hx_new(LevelTest.prototype)
  LevelTest.super(self)
  return self
end
LevelTest.super = function(self) 
  __defold_support_Script.super(self);
end
LevelTest.prototype = _hx_e();
LevelTest.prototype.init = function(self,_self) 
  _G.msg.post(".", __defold_GoMessages.acquire_input_focus);
  local grid = _hx_tab_array({}, 0);
  local _hx_1_bounds_x, _hx_1_bounds_y, _hx_1_bounds_w, _hx_1_bounds_h = _G.tilemap.get_bounds("#map");
  local _g = 3;
  local _g1 = _hx_1_bounds_h + 1;
  while (_g < _g1) do 
    _g = _g + 1;
    local y = _g - 1;
    local row = _hx_tab_array({}, 0);
    local _g = 3;
    local _g1 = _hx_1_bounds_w + 1;
    while (_g < _g1) do 
      _g = _g + 1;
      row:push(1);
      _G.tilemap.set_tile("#map", "layer1", _g - 1, y, 1);
    end;
    grid:push(row);
  end;
  _self.pathfinding = __astar_PathFinding.new(grid, LevelTest.walkable);
  _self.currentTileIndex = 0;
  _self.start = nil;
  _self.goal = nil;
end
LevelTest.prototype.final_ = function(self,_self) 
  _G.msg.post(".", __defold_GoMessages.release_input_focus);
end
LevelTest.prototype.on_message = function(self,_self,message_id,message,sender) 
  if (message_id) == Messages.buildBase then 
    _self.newBuilding = _G.factory.create("/factories#basefactory", _G.vmath.vector3(0, 64, 0.1));
    _self.base = true;
  elseif (message_id) == Messages.buildTower then 
    _self.newBuilding = _G.factory.create("/factories#towerfactory", _G.vmath.vector3(0, 0, 0.1)); end;
end
LevelTest.prototype.on_input = function(self,_self,action_id,action) 
  if ((action_id == nil) and (_self.newBuilding ~= nil)) then 
    local worldPos = Camera.toWorld(action.x, action.y);
    local x = _G.math.ceil(worldPos.x / LevelTest.TILE_SIZE);
    local y = _G.math.ceil(worldPos.y / LevelTest.TILE_SIZE);
    if (_self.base) then 
      _G.go.set_position(_G.vmath.vector3(x * 32, y * 32, 0.1), _self.newBuilding);
    else
      _G.go.set_position(_G.vmath.vector3((x * 32) - 16, (y * 32) - 16, 0.1), _self.newBuilding);
    end;
  end;
  if (((action_id == LevelTest.TOUCH) and action.pressed) and (_self.newBuilding ~= nil)) then 
    _self.newBuilding = nil;
    _self.base = false;
  end;
  do return false end
end
LevelTest.__super__ = __defold_support_Script
setmetatable(LevelTest.prototype,{__index=__defold_support_Script.prototype})

Loader.new = function() 
  local self = _hx_new(Loader.prototype)
  Loader.super(self)
  return self
end
Loader.super = function(self) 
  __defold_support_Script.super(self);
end
Loader.prototype = _hx_e();
Loader.prototype.init = function(self,_self) 
  _G.math.randomseed(_G.os.time());
  _G.math.random(0, 1);
  _G.msg.post(".", __defold_GoMessages.acquire_input_focus);
  self:loadCollection(_self, "#game");
end
Loader.prototype.final_ = function(self,_self) 
  _G.msg.post(".", __defold_GoMessages.release_input_focus);
end
Loader.prototype.on_message = function(self,_self,message_id,message,sender) 
  if (message_id) == Messages.changeCollection then 
    _self.nextCollection = _hx_funcToField(message.collection);
    self:unloadCollection(_self.currentCollection);
  elseif (message_id) == __defold_CollectionproxyMessages.proxy_loaded then 
    _G.msg.post(sender, __defold_CollectionproxyMessages.init);
    _G.msg.post(sender, __defold_CollectionproxyMessages.enable);
  elseif (message_id) == __defold_CollectionproxyMessages.proxy_unloaded then 
    self:loadCollection(_self, _self.nextCollection); end;
end
Loader.prototype.loadCollection = function(self,_self,collection) 
  _self.currentCollection = collection;
  _G.msg.post(collection, __defold_CollectionproxyMessages.load);
end
Loader.prototype.unloadCollection = function(self,collection) 
  _G.msg.post(collection, __defold_CollectionproxyMessages.unload);
end
Loader.__super__ = __defold_support_Script
setmetatable(Loader.prototype,{__index=__defold_support_Script.prototype})

Math.new = {}
Math.isNaN = function(f) 
  do return f ~= f end;
end
Math.isFinite = function(f) 
  if (f > -_G.math.huge) then 
    do return f < _G.math.huge end;
  else
    do return false end;
  end;
end
Math.min = function(a,b) 
  if (Math.isNaN(a) or Math.isNaN(b)) then 
    do return (0/0) end;
  else
    do return _G.math.min(a, b) end;
  end;
end

Messages.new = {}

__astar_Node.new = function(x,y,tileIndex,weight) 
  local self = _hx_new()
  __astar_Node.super(self,x,y,tileIndex,weight)
  return self
end
__astar_Node.super = function(self,x,y,tileIndex,weight) 
  if (weight == nil) then 
    weight = 1;
  end;
  self.x = x;
  self.y = y;
  self.tileIndex = tileIndex;
  self.weight = weight;
end

__astar_PathFinding.new = function(grid,walkableTiles) 
  local self = _hx_new(__astar_PathFinding.prototype)
  __astar_PathFinding.super(self,grid,walkableTiles)
  return self
end
__astar_PathFinding.super = function(self,grid,walkableTiles) 
  self.pointsToAvoid = _hx_tab_array({}, 0);
  local _g = 0;
  local _g1 = grid.length;
  while (_g < _g1) do 
    _g = _g + 1;
    local row = _hx_tab_array({}, 0);
    local _g = 0;
    local _g1 = grid[0].length;
    while (_g < _g1) do 
      _g = _g + 1;
      row:push(0);
    end;
    self.pointsToAvoid:push(row);
  end;
  self.walkableTiles = walkableTiles;
  self:updateGrid(grid);
  self.queue = __haxe_ds_List.new();
end
__astar_PathFinding.prototype = _hx_e();
__astar_PathFinding.prototype.updateGrid = function(self,grid) 
  self.grid = _hx_tab_array({}, 0);
  local _g = 0;
  local _g1 = grid.length;
  while (_g < _g1) do 
    _g = _g + 1;
    local y = _g - 1;
    local row = _hx_tab_array({}, 0);
    local _g = 0;
    local _g1 = grid[0].length;
    while (_g < _g1) do 
      _g = _g + 1;
      local x = _g - 1;
      row:push(__astar_Node.new(x, y, grid[y][x]));
    end;
    self.grid:push(row);
  end;
end

__astar_Point.new = {}

__defold_CameraMessages.new = {}

__defold_CollectionproxyMessages.new = {}

__defold_GoMessages.new = {}

__defold_RenderMessages.new = {}

__defold_support_GuiScript.new = function() 
  local self = _hx_new()
  __defold_support_GuiScript.super(self)
  return self
end
__defold_support_GuiScript.super = function(self) 
end

__gui_GameGui.new = function() 
  local self = _hx_new(__gui_GameGui.prototype)
  __gui_GameGui.super(self)
  return self
end
__gui_GameGui.super = function(self) 
  __defold_support_GuiScript.super(self);
end
__gui_GameGui.prototype = _hx_e();
__gui_GameGui.prototype.init = function(self,_self) 
  _G.msg.post(".", __defold_GoMessages.acquire_input_focus);
end
__gui_GameGui.prototype.final_ = function(self,_self) 
  _G.msg.post(".", __defold_GoMessages.release_input_focus);
end
__gui_GameGui.prototype.on_input = function(self,_self,action_id,action) 
  if ((action_id == __gui_GameGui.TOUCH) and action.pressed) then 
    local baseButton = _G.gui.get_node("base");
    local towerButton = _G.gui.get_node("tower");
    local mine = _G.gui.get_node("mine");
    local barracks = _G.gui.get_node("barracks");
    local wall = _G.gui.get_node("wall");
    if (_G.gui.pick_node(baseButton, action.x, action.y)) then 
      _G.msg.post("/map", Messages.buildBase);
    else
      if (_G.gui.pick_node(towerButton, action.x, action.y)) then 
        _G.msg.post("/map", Messages.buildTower);
      else
        if (_G.gui.pick_node(mine, action.x, action.y)) then 
          _G.msg.post("/map", Messages.buildMine);
        else
          if (_G.gui.pick_node(barracks, action.x, action.y)) then 
            _G.msg.post("/map", Messages.buildBarracks);
          else
            if (_G.gui.pick_node(wall, action.x, action.y)) then 
              __haxe_Log.trace("pressed wall", _hx_o({__fields__={fileName=true,lineNumber=true,className=true,methodName=true},fileName="src/gui/GameGui.hx",lineNumber=46,className="gui.GameGui",methodName="on_input"}));
            end;
          end;
        end;
      end;
    end;
  end;
  do return false end
end
__gui_GameGui.__super__ = __defold_support_GuiScript
setmetatable(__gui_GameGui.prototype,{__index=__defold_support_GuiScript.prototype})

__defold_support_RenderScript.new = function() 
  local self = _hx_new()
  __defold_support_RenderScript.super(self)
  return self
end
__defold_support_RenderScript.super = function(self) 
end

__renderer_Renderer.new = function() 
  local self = _hx_new(__renderer_Renderer.prototype)
  __renderer_Renderer.super(self)
  return self
end
__renderer_Renderer.super = function(self) 
  __defold_support_RenderScript.super(self);
end
__renderer_Renderer.prototype = _hx_e();
__renderer_Renderer.prototype.init = function(self,_self) 
  _self.tilePred = _G.render.predicate(({"tile"}));
  _self.guiPred = _G.render.predicate(({"gui"}));
  _self.textPred = _G.render.predicate(({"text"}));
  _self.particlePred = _G.render.predicate(({"particle"}));
  _self.clearColor = _G.vmath.vector4(0, 0, 0, 0);
  local tmp = _G.sys.get_config("render.clear_color_red", "0");
  _self.clearColor.x = _G.tonumber(tmp);
  local tmp = _G.sys.get_config("render.clear_color_green", "0");
  _self.clearColor.y = _G.tonumber(tmp);
  local tmp = _G.sys.get_config("render.clear_color_blue", "0");
  _self.clearColor.z = _G.tonumber(tmp);
  local tmp = _G.sys.get_config("render.clear_color_alpha", "0");
  _self.clearColor.w = _G.tonumber(tmp);
  _self.view = _G.vmath.matrix4();
  _self.clearData = ({});
  _G.table.insert(_self.clearData, _G.render.BUFFER_COLOR_BIT, _self.clearColor);
  _G.table.insert(_self.clearData, _G.render.BUFFER_DEPTH_BIT, 1);
  _G.table.insert(_self.clearData, _G.render.BUFFER_STENCIL_BIT, 0);
  _self.designWidth = 960;
  _self.designHeight = 640;
  _self.currentSize = _hx_o({__fields__={width=true,height=true},width=0,height=0});
  _self.projectedSize = _hx_o({__fields__={width=true,height=true},width=0,height=0});
  _self.offset = _G.vmath.vector3(0, 0, 0);
end
__renderer_Renderer.prototype.update = function(self,_self,dt) 
  _G.render.set_depth_mask(true);
  _self.clearData[_G.render.BUFFER_COLOR_BIT] = _self.clearColor;
  _G.render.clear(_self.clearData);
  _self.currentSize.width = _G.render.get_window_width();
  _self.currentSize.height = _G.render.get_window_height();
  _G.render.set_viewport(0, 0, Std.int(_self.currentSize.width), Std.int(_self.currentSize.height));
  _G.render.set_view(_self.view);
  _G.render.set_depth_mask(false);
  _G.render.disable_state(_G.render.STATE_DEPTH_TEST);
  _G.render.disable_state(_G.render.STATE_STENCIL_TEST);
  _G.render.enable_state(_G.render.STATE_BLEND);
  _G.render.set_blend_func(_G.render.BLEND_SRC_ALPHA, _G.render.BLEND_ONE_MINUS_SRC_ALPHA);
  _G.render.disable_state(_G.render.STATE_CULL_FACE);
  local zoom = __renderer_RenderHelper.instance.zoom;
  local tmp = _G.math.floor(_self.currentSize.width / zoom);
  _self.projectedSize.width = tmp;
  local tmp = _G.math.floor(_self.currentSize.height / zoom);
  _self.projectedSize.height = tmp;
  local self1 = _self.projectedSize.width;
  local tmp = _G.render.get_width();
  _self.offset.x = -(self1 - tmp) * 0.5;
  local self1 = _self.projectedSize.height;
  local tmp = _G.render.get_height();
  _self.offset.y = -(self1 - tmp) * 0.5;
  _G.render.set_projection(_G.vmath.matrix4_orthographic(_self.offset.x, _self.offset.x + _self.projectedSize.width, _self.offset.y, _self.offset.y + _self.projectedSize.height, -1, 1));
  __renderer_RenderHelper.instance.xOffset = _self.offset.x;
  __renderer_RenderHelper.instance.yOffset = _self.offset.y;
  __renderer_RenderHelper.instance.viewWidth = _hx_funcToField(_self.projectedSize.width);
  __renderer_RenderHelper.instance.viewHeight = _hx_funcToField(_self.projectedSize.height);
  _G.render.draw(_self.tilePred);
  _G.render.draw(_self.particlePred);
  _G.render.draw_debug3d();
  _G.render.set_view(_G.vmath.matrix4());
  _G.render.set_projection(_G.vmath.matrix4_orthographic(0, _self.currentSize.width, 0, _self.currentSize.height, -1, 1));
  _G.render.enable_state(_G.render.STATE_STENCIL_TEST);
  _G.render.draw(_self.guiPred);
  _G.render.draw(_self.textPred);
  _G.render.disable_state(_G.render.STATE_STENCIL_TEST);
  _G.render.set_depth_mask(false);
end
__renderer_Renderer.prototype.on_message = function(self,_self,message_id,message,sender) 
  if (message_id) == __defold_RenderMessages.clear_color then 
    _self.clearColor = _hx_funcToField(message.color);
  elseif (message_id) == __defold_RenderMessages.set_view_projection then 
    _self.view = _hx_funcToField(message.view); end;
end
__renderer_Renderer.__super__ = __defold_support_RenderScript
setmetatable(__renderer_Renderer.prototype,{__index=__defold_support_RenderScript.prototype})

__defold_support_Init.new = {}
__defold_support_Init.init = function(exports) 
  local script = Loader.new();
  exports.Loader_init = function(_self) 
    script:init(_self);
  end;
  exports.Loader_final_ = function(_self) 
    script:final_(_self);
  end;
  exports.Loader_on_message = function(_self,message_id,message,sender) 
    script:on_message(_self, message_id, message, sender);
  end;
  local script = __gui_GameGui.new();
  exports.gui_GameGui_init = function(_self) 
    script:init(_self);
  end;
  exports.gui_GameGui_final_ = function(_self) 
    script:final_(_self);
  end;
  exports.gui_GameGui_on_input = function(_self,action_id,action) 
    do return script:on_input(_self, action_id, action) end;
  end;
  local script = LevelTest.new();
  exports.LevelTest_init = function(_self) 
    script:init(_self);
  end;
  exports.LevelTest_final_ = function(_self) 
    script:final_(_self);
  end;
  exports.LevelTest_on_message = function(_self,message_id,message,sender) 
    script:on_message(_self, message_id, message, sender);
  end;
  exports.LevelTest_on_input = function(_self,action_id,action) 
    do return script:on_input(_self, action_id, action) end;
  end;
  local script = __renderer_Renderer.new();
  exports.renderer_Renderer_init = function(_self) 
    script:init(_self);
  end;
  exports.renderer_Renderer_update = function(_self,dt) 
    script:update(_self, dt);
  end;
  exports.renderer_Renderer_on_message = function(_self,message_id,message,sender) 
    script:on_message(_self, message_id, message, sender);
  end;
  local script = Camera.new();
  exports.Camera_init = function(_self) 
    script:init(_self);
  end;
  exports.Camera_final_ = function(_self) 
    script:final_(_self);
  end;
  exports.Camera_on_input = function(_self,action_id,action) 
    do return script:on_input(_self, action_id, action) end;
  end;
end

__haxe_Log.new = {}
__haxe_Log.formatOutput = function(v,infos) 
  local str = Std.string(v);
  if (infos == nil) then 
    do return str end;
  end;
  local pstr = Std.string(Std.string(infos.fileName) .. Std.string(":")) .. Std.string(infos.lineNumber);
  if (infos.customParams ~= nil) then 
    local _g = 0;
    local _g1 = infos.customParams;
    while (_g < _g1.length) do 
      local v = _g1[_g];
      _g = _g + 1;
      str = Std.string(str) .. Std.string((Std.string(", ") .. Std.string(Std.string(v))));
    end;
  end;
  do return Std.string(Std.string(pstr) .. Std.string(": ")) .. Std.string(str) end;
end
__haxe_Log.trace = function(v,infos) 
  local str = __haxe_Log.formatOutput(v, infos);
  _hx_print(str);
end

__haxe_ds_List.new = function() 
  local self = _hx_new()
  __haxe_ds_List.super(self)
  return self
end
__haxe_ds_List.super = function(self) 
  self.length = 0;
end

__haxe_iterators_ArrayIterator.new = function(array) 
  local self = _hx_new(__haxe_iterators_ArrayIterator.prototype)
  __haxe_iterators_ArrayIterator.super(self,array)
  return self
end
__haxe_iterators_ArrayIterator.super = function(self,array) 
  self.current = 0;
  self.array = array;
end
__haxe_iterators_ArrayIterator.prototype = _hx_e();
__haxe_iterators_ArrayIterator.prototype.hasNext = function(self) 
  do return self.current < self.array.length end
end
__haxe_iterators_ArrayIterator.prototype.next = function(self) 
  do return self.array[(function() 
  local _hx_obj = self;
  local _hx_fld = 'current';
  local _ = _hx_obj[_hx_fld];
  _hx_obj[_hx_fld] = _hx_obj[_hx_fld]  + 1;
   return _;
   end)()] end
end

__haxe_iterators_ArrayKeyValueIterator.new = function(array) 
  local self = _hx_new()
  __haxe_iterators_ArrayKeyValueIterator.super(self,array)
  return self
end
__haxe_iterators_ArrayKeyValueIterator.super = function(self,array) 
  self.array = array;
end

__renderer_RenderHelper.new = function() 
  local self = _hx_new(__renderer_RenderHelper.prototype)
  __renderer_RenderHelper.super(self)
  return self
end
__renderer_RenderHelper.super = function(self) 
  self.viewHeight = 0.0;
  self.viewWidth = 0.0;
  self.zoom = 1.0;
  self.yOffset = 0.0;
  self.xOffset = 0.0;
end
__renderer_RenderHelper.prototype = _hx_e();
__renderer_RenderHelper.prototype.screenToWorld = function(self,x,y,out) 
  if (out ~= nil) then 
    out.x = self.xOffset + (x / self.zoom);
    out.y = self.yOffset + (y / self.zoom);
    out.z = 0;
    do return out end;
  end;
  do return _G.vmath.vector3(self.xOffset + (x / self.zoom), self.yOffset + (y / self.zoom), 0) end
end
if _hx_bit_raw then
    _hx_bit_clamp = function(v)
    if v <= 2147483647 and v >= -2147483648 then
        if v > 0 then return _G.math.floor(v)
        else return _G.math.ceil(v)
        end
    end
    if v > 2251798999999999 then v = v*2 end;
    if (v ~= v or math.abs(v) == _G.math.huge) then return nil end
    return _hx_bit_raw.band(v, 2147483647 ) - math.abs(_hx_bit_raw.band(v, 2147483648))
    end
else
    _hx_bit_clamp = function(v)
        if v < -2147483648 then
            return -2147483648
        elseif v > 2147483647 then
            return 2147483647
        elseif v > 0 then
            return _G.math.floor(v)
        else
            return _G.math.ceil(v)
        end
    end
end;



_hx_array_mt.__index = Array.prototype

local _hx_static_init = function()
  
  _hxdefold_ = _hxdefold_ or {}
  __defold_support_Init.init(_hxdefold_);Camera.WHEEL_DOWN = _G.hash("wheel_down");
  
  Camera.WHEEL_UP = _G.hash("wheel_up");
  
  Camera.MIN_ZOOM = 0.5;
  
  Camera.MAX_ZOOM = 2;
  
  LevelTest.TILE_SIZE = 32;
  
  LevelTest.TOUCH = _G.hash("touch");
  
  LevelTest.walkable = _hx_tab_array({[0]=1, 3, 4, 5}, 4);
  
  Messages.changeCollection = _G.hash("changeCollection");
  
  Messages.buildBase = _G.hash("buildBase");
  
  Messages.buildTower = _G.hash("buildTower");
  
  Messages.buildMine = _G.hash("buildMine");
  
  Messages.buildBarracks = _G.hash("buildBarracks");
  
  __defold_CameraMessages.acquire_camera_focus = _G.hash("acquire_camera_focus");
  
  __defold_CollectionproxyMessages.enable = _G.hash("enable");
  
  __defold_CollectionproxyMessages.init = _G.hash("init");
  
  __defold_CollectionproxyMessages.load = _G.hash("load");
  
  __defold_CollectionproxyMessages.proxy_loaded = _G.hash("proxy_loaded");
  
  __defold_CollectionproxyMessages.proxy_unloaded = _G.hash("proxy_unloaded");
  
  __defold_CollectionproxyMessages.unload = _G.hash("unload");
  
  __defold_GoMessages.acquire_input_focus = _G.hash("acquire_input_focus");
  
  __defold_GoMessages.release_input_focus = _G.hash("release_input_focus");
  
  __defold_RenderMessages.clear_color = _G.hash("clear_color");
  
  __defold_RenderMessages.set_view_projection = _G.hash("set_view_projection");
  
  __gui_GameGui.TOUCH = _G.hash("touch");
  
  __renderer_RenderHelper.instance = __renderer_RenderHelper.new();
  
  
end

_hx_funcToField = function(f)
  if type(f) == 'function' then
    return function(self,...)
      return f(...)
    end
  else
    return f
  end
end

_hx_print = print or (function() end)

_hx_static_init();
